---
title: "data_import"
author: "Tian Li"
date: 09/18/2018
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv")
col_types = "ccddiiii"
#litters_data = read_csv(file = "./data/FAS_litters.csv", skip = 10, col_names = FALSE)

litters_data = janitor::clean_names(litters_data)
skimr::skim(litters_data)
```

```{r}
head(litters_data)
tail(litters_data)
```

```{r try}
litters_data = read_csv(file = "./data/FAS_litters.csv")
col_types = "ciiiii"
litters_data = janitor::clean_names(litters_data)
skimr::skim(litters_data)
```

```{r}
mlb_data = readxl::read_excel(path = "./data/mlb11.xlsx", range = "A1:E17")
pulse_data = haven::read_sas("./data/public_pulse_data.sas7bdat")
head(pulse_data, 5)
```

```{r}
pups_base = read.csv("./data/FAS_pups.csv")
pups_readr = read_csv("./data/FAS_pups.csv")

View(pups_base)
View(pups_readr)

pups_base
pups_readr

pups_base$S
pups_readr$S
```

